### ISSUE TITLE
Maven 3 ppa missing

### ISSUE THREAD

**Issue by ronna** [jefferyb/kuali-coeus#3]
Hi Jeffery,

The maven 3 ppa is missing:

W: Failed to fetch http://ppa.launchpad.net/andrei-pozolotin/maven3/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found

**Comment by jefferyb** [comment]
Hi Ronald,
I've updated the script and should be able to compile without any issues... Try it out and let me know...
Thanks for reporting the issue...
Jeffery
